### ISSUE TITLE
Composer install don't downloading its dependency

### ISSUE THREAD

**Issue by gunytalk** [theseer/phpdox#129]
1)Trying to install phpdox through composer
"theseer/phpdox": "*"
Following Error occured:
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - theseer/phpdox 0.6.3 requires theseer/fxsl >=1.0 -> no matching package found.
    - theseer/phpdox 0.6.2 requires theseer/fxsl >=1.0 -> no matching package found.
    - theseer/phpdox 0.6.1 requires theseer/fxsl >=1.0 -> no matching package found.
    - theseer/phpdox 0.6 requires theseer/fxsl >=1.0 -> no matching package found.
    - Installation request for theseer/phpdox \* -> satisfiable by theseer/phpdox[0.6, 0.6.1, 0.6.2, 0.6.3].

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

Read http://getcomposer.org/doc/articles/troubleshooting.md for further common problems.
2)Tried to install throug git and set the environment variable

ERROR 
'"@php_bin@"' is not recognized as an internal or external command,
operable program or batch file.

Trying to install all these as a part of setup jenkin

**Comment by abhijeetka** [comment]
Unable to install phpdox using composer.

**Comment by theseer** [comment]
I cannot see any issues:

```
theseer@nyda ~/Desktop/issue129 $ composer require theseer/phpdox
Using version 0.8.1.1 for theseer/phpdox
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing nikic/php-parser (v1.3.0)
    Loading from cache

  - Installing phpunit/php-timer (1.0.6)
    Loading from cache

  - Installing theseer/fxsl (1.1.1)
    Loading from cache

  - Installing theseer/directoryscanner (1.3.1)
    Loading from cache

  - Installing theseer/fdomdocument (1.6.1)
    Loading from cache

  - Installing theseer/phpdox (0.8.1.1)
    Downloading: 100%         

Writing lock file
Generating autoload files
```

```
theseer@nyda ~/Desktop/issue129 $ ll
total 16
-rw-rw-r--. 1 theseer theseer   63 17. Jul 08:46 composer.json
-rw-rw-r--. 1 theseer theseer 9898 17. Jul 08:46 composer.lock
drwxrwxr-x. 7 theseer theseer   90 17. Jul 08:46 vendor
```

```
theseer@nyda ~/Desktop/xxx $ ./vendor/bin/phpdox  --version
phpDox 0.8.2-dev - Copyright (C) 2010 - 2015 by Arne Blankerts
```

Works like charm.

If you continue to have issues, open a new ticket and provide additional information.
