### ISSUE TITLE
encoder error

### ISSUE THREAD

**Issue by guckykv** [theseer/phpdox#160]
Tried latest version - installed via composer "theseer/phpdox": "*"

     [exec] [26.08.2014 - 18:37:10] Saving results to directory '/vagrant/xxx/yyy/build/phpdox/xml'
     [exec] 
     [exec] 
     [exec] Oups... phpDox encountered a problem and has terminated!
     [exec] 
     [exec] It most likely means you've found a bug, so please file a report for this
     [exec] and paste the following details and the stacktrace (if given) along:
     [exec] 
     [exec] PHP Version: 5.4.30-2+deb.sury.org~precise+1 (Linux)
     [exec] PHPDox Version: REL-3400-33-gb72f211-dirty
     [exec] Exception: TheSeer\fDOM\fDOMException (Code: 3)
     [exec] Location: /vagrant/xxx/yyy/vendor/theseer/fdomdocument/src/fDOMDocument.php (Line 234)
     [exec] 
     [exec] saving xml file failed
     [exec] 
     [exec] [XML-STRING] [Line: 0 - Column: 0] Fatal Error 6003: output conversion failed due to conv error, bytes 0xA0 0x7B 0x40 0x69
     [exec] [XML-STRING] [Line: 0 - Column: 0] Error 1544: encoder error
     [exec] 
     [exec] 
     [exec] #0 /vagrant/xxx/yyy/vendor/theseer/phpdox/src/Application.php(138): TheSeer\phpDox\Collector\Project->save()
     [exec] #1 /vagrant/xxx/yyy/vendor/theseer/phpdox/src/CLI.php(148): TheSeer\phpDox\Application->runCollector()
     [exec] #2 /vagrant/xxx/yyy/vendor/theseer/phpdox/composer/bin/phpdox(30): TheSeer\phpDox\CLI->run()

**Comment by theseer** [comment]
This should be fixed with commits 2c3daee7bc62f505520cd3f61a4710184a0fb838 and 7b5ae1a9078d623028a38bbec111832ab5b062f2 for good.
