### ISSUE TITLE
makedir() problem if not root user / AbstractEngine

### ISSUE THREAD

**Issue by 1605200517** [theseer/phpdox#178]
As part of an ant script, phpdox executes successfully in root mode. 
However as Jenkins there is some problem with an existing directory (access rights completely set to same user as script runner i.e. jenkins)

![phpdox_bug](https://cloud.githubusercontent.com/assets/1834666/5228323/d1f4955c-7708-11e4-9b4d-98fab2566786.png)

**Comment by iwankgb** [comment]
I have just upgraded phpdox to current master and the problem disappeared.

**Comment by theseer** [comment]
Thanks for the heads up.
