### ISSUE TITLE
Phploc question

### ISSUE THREAD

**Issue by mpaleo** [theseer/phpdox#184]
Hi there,
how can i get phploc working ?
The html is working but it says this:
Warning: PHPLoc enrichment not enabled or phploc.xml not found.

And i get this when i run phpdox
PHPLoc xml file "/home/mpaleo/Desktop/app/build/phploc.xml" not found.

Thanks

**Comment by matjung** [comment]
PHPLoc enrichment not enabled or phploc.xml not found.

I will check in 2020 if the solution from 2014 is still working.

Enrichers tells me that phploc is registered - where I never installed that external tool.

phpdox-0.11.2.phar --enrichers

The following enrichers are registered:
   build         Build information enricher
   git   GIT repository information enricher
   checkstyle    checkstyle.xml enricher
   phpcs         phpcs.xml enricher
   pmd   PHPMessDetector (pmd.xml) enricher
   phpunit       PHPUnit code coverage enricher
   phploc        PHPLoc code statistic enricher

**Comment by theseer** [comment]
What is the question/issue here?

The *enricher* is part of phpdox, phploc itself is not. The enricher can be active but of course to do anything useful, it needs the output generated by phploc. Running phploc is out of scope from phpdox, as phpdox is not a build environment.
