### ISSUE TITLE
avoid exit() calls

### ISSUE THREAD

**Issue by renanbr** [theseer/phpdox#186]
Trying to instance [`TheSeer\phpDox\CLI`](https://github.com/theseer/phpdox/blob/master/src/CLI.php) directly, so then when some exception occurs in `run()` method, it gives up my execution. I would like to receive the __already well defined__ exceptions and handle them by myself. Does it fit to the project goals?

ps: the same occurs in `TheSeer\phpDox\ErrorHandler::handleException()`
ps: i'm using master branch because Factories classes are better

**Comment by theseer** [comment]
While i won't change the exit calls for the above reasons, the CLI class still does to many things that are not really CLI specific and thus should get moved out.

I'll look into that and thus keep this ticket open as a reminder for now.

**Comment by theseer** [comment]
Implemented with commits 054a067dcd8cdd511201111114bdf9c19a4df683, 5715bee9d7e57d55a970099a958c7ba51b5eb7e5 and d825ed37dcccbd49e4c113d9da66cf96c0509c83
