### ISSUE TITLE
Binary no longer compatible with PHP >= 5.3.3

### ISSUE THREAD

**Issue by DannyvdSluijs** [theseer/phpdox#192]
The code in:

https://github.com/theseer/phpdox/blob/master/phpdox#L62

```php
(new TheSeer\phpDox\Factory())->getCLI()->run(
    new TheSeer\phpDox\CLIOptions($_SERVER['argv'])
);
```

Doesn't work on a PHP 5.3.10 installation.My other installation with 5.5.14 works without problems.

Either correct the dependancy or correct the code:

```php
$factory = new TheSeer\phpDox\Factory();
$factory->getCLI()->run(
    new TheSeer\phpDox\CLIOptions($_SERVER['argv'])
);
```
Would make it compatible with 5.3.3 I would chose this option as still quite some 5.3.* installations are out there.

**Comment by theseer** [comment]
This is actually fixed with the merge of d65bd828b11659c77e562a95f8af4ac5c50f2ea0 and will be part of 0.8.0

**Comment by jdespatis** [comment]
I have the same problem, we still have php 5.3 on our CI server

Any idea when the 0.8.0 will be released?

**Comment by theseer** [comment]
I'm going to finally have some time next week again. Already fixed some issues again and hope to make a release next week.
