### ISSUE TITLE
encountering bug in NodeAbstract.php

### ISSUE THREAD

**Issue by mdichirico** [theseer/phpdox#195]
[exec] Oups... phpDox encountered a problem and has terminated!
     [exec] 
     [exec] It most likely means you've found a bug, so please file a report for this
     [exec] and paste the following details and the stacktrace (if given) along:
     [exec] 
     [exec] PHP Version: 5.6.4 (Linux)
     [exec] PHPDox Version: 0.7.0
     [exec] ErrorException: E_ERROR 
     [exec] Location: phar:///usr/bin/phpdox/PHP-Parser-1.0.0beta1/lib/PhpParser/NodeAbstract.php (Line 113)
     [exec] 
     [exec] Allowed memory size of 2147483648 bytes exhausted (tried to allocate 32 bytes)
     [exec] 
     [exec] No stacktrace available

By all means, please let me know if more information is needed. Thanks.

**Comment by theseer** [comment]
Can you verify if that problem still exists in dev/master with PHP-Parser 1.0.2?
If it does, I'd like to get a reproducible testcase to forward it to nickic.

**Comment by mdichirico** [comment]
I'll have an update for you no later than Sunday (2015-01-18). Thanks.

**Comment by mdichirico** [comment]
I updated to PHP-Parser 1.0.2. I have run my Jenkins build a few times and the phpDox section no longer encounters that issue. It works normally. Thanks.
