### ISSUE TITLE
Oups : call to undefined method

### ISSUE THREAD

**Issue by tdegouw** [theseer/phpdox#200]
Trying out phpdoc on one of the project to see if it can replace phpdocumentor. This error occured the first run, subsequent runs did not give the error and generation finished succesfully.

PHP Version: 5.4.24 (Linux)
PHPDox Version: 0.7.0
ErrorException: E_ERROR 
Location: phar:////usr/local/bin/phpdox.phar/phpdox/collector/InheritanceResolver.php (Line 169)

Call to undefined method TheSeer\phpDox\Collector\ClassObject::addImplementor()

No stacktrace available

**Comment by theseer** [comment]
Can you verify if that still happens with the current master?

**Comment by tdegouw** [comment]
Checked : Current master is fine.

**Comment by theseer** [comment]
Thanks. That means I can close this issue as 0.8.0 is going to be released soon, including a fix for this.
