### ISSUE TITLE
Potential Bug php 5.3.10 E_CORE_WARNING

### ISSUE THREAD

**Issue by spencer-aerian** [theseer/phpdox#203]
Running phpdox or even phpdox --skel or --help I get 

Oups... phpDox encountered a problem and has terminated!

It most likely means you've found a bug, so please file a report for this
and paste the following details and the stacktrace (if given) along:

PHP Version: 5.3.10-1ubuntu3.16 (Linux)
PHPDox Version: 0.7.0-95-gc9763a3
ErrorException: E_CORE_WARNING 
Location: Unknown (Line 0)

Module 'memcache' already loaded

No stacktrace available

Works fine on my virtual machine, but when running on my integration server via a script within jenkins I get the above error.

**Comment by theseer** [comment]
This is not exactly a bug in phpDox but a configuration issue with your environment. phpDox just happens to be very strict with error handling and the misconfiguration is (sadly) reported to userland thus phpDox' error handler picks it up.

You can verify that by running php on the command line, e.g. like this:
```
theseer@nyda ~ $ php -v
```

That will return something like this:
```
PHP Warning:  Module 'memcache' already loaded in Unknown on line 0
PHP 5.6.5 (cli) (built: Jan 21 2015 17:04:06) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2014 Zend Technologies
    with Xdebug v2.2.7, Copyright (c) 2002-2015, by Derick Rethans
```

You, for whatever reason, have the extension "memcache" loaded twice, which doesn't work of course.

**Comment by spencer-aerian** [comment]
Many thanks.
