### ISSUE TITLE
how i can edit the template

### ISSUE THREAD

**Issue by qa-rodolfocordero** [theseer/phpdox#204]
Hi, i want to personalize the template generated, how i can edit the files

**Comment by theseer** [comment]
The (html) templates are located in their own folder and come bundled with the phpDox phar.
If you don't like or need/want to modify them, using the phpdox.xml you can specify a path to where a custom set of files can be found.
To get you started, you can have a look at the original files located here:
https://github.com/theseer/phpdox/tree/master/templates/html 

In case you consider your customization to be of general use, feel free to make a pull request.
