### ISSUE TITLE
Backward incompatible change

### ISSUE THREAD

**Issue by iwankgb** [theseer/phpdox#207]
https://github.com/theseer/phpdox/commit/8b92fd59092ac5f2a4ee8db7f1775205abc3beff introduced a backward incompatible change. You need to change XML namespace declaration from http://phpdox.net/config to http://xml.phpdox.net/config.

I don't think it's a bug but it would be good to have this changed documented in order to make migration to new version (whenever it is released) easier.

**Comment by theseer** [comment]
I uses to have a notice for the outdated namespace and thought it could be removed from now on.

Regarding release: I'm trying hard to get the release out. I have currently two outstanding issues that I want to have included but not enough time to work on them right now. I hope to be done soon with that and will definitely include a note regarding the namespace. Thank you for reminding me!

**Comment by theseer** [comment]
The config handling has been adjusted to be "nice" on namespace related issues and give a (helpful) error message.
