### ISSUE TITLE
class constants of type boolean are not fetched

### ISSUE THREAD

**Issue by kungtiger** [theseer/phpdox#208]
First things first: great thing of yours!
Took me a bit to get it to work but in the end I figured it out.

But: One of my classes is defining some constants and are of type boolean.
In the final Documentation their values do not show up. The table cell is simply empty.
I've checked the XMLs phpDox is generating and it turnes out that neither true nor false are recognised.

Maybe you could fix it, otherwise I will edit the XML file manually and run the generation again.

Thanks!

**Comment by theseer** [comment]
This was due to an (at least to me) unexpected behavior of PHPParser. Found the issue and reworked the code to be more reliable and fixed a bunch of other issues with that along.

Works for me now.
