### ISSUE TITLE
Oups... phpDox encountered a problem and has terminated!

### ISSUE THREAD

**Issue by ecavalier** [theseer/phpdox#210]
in windows 8.1 
I'm using phar and 
that's my patch file

@ECHO OFF
SET BIN_TARGET=%~dp0phpdox.phar
php "%BIN_TARGET%" %*

[exec] Oups... phpDox encountered a problem and has terminated!
     [exec] 
     [exec] It most likely means you've found a bug, so please file a report for this
     [exec] and paste the following details and the stacktrace (if given) along:
     [exec] 
     [exec] PHP Version: 5.6.3 (WINNT)
     [exec] PHPDox Version: 0.7.0
     [exec] Exception: TheSeer\fXSL\fXSLTProcessorException (Code: 2)
     [exec] Location: phar://K:/phptools/phpdox.phar/fXSL-1.0.4/TheSeer/fXSL/fxsltprocessor.php (Line 251)
     [exec] 
     [exec] Error while importing given stylesheet

Thank you in advance

**Comment by theseer** [comment]
Would it be possible to verify with a custom-build based on dev-master and see, wether this problem still exists? I don't have a Windows 8.x maschine to verify.

**Comment by theseer** [comment]
Ping?

**Comment by theseer** [comment]
No Feedback provided.
