### ISSUE TITLE
 Compilation failed: support for \P, \p, and \X has not been compiled at offset 31

### ISSUE THREAD

**Issue by dogstarTest** [theseer/phpdox#211]
Hi,

after i installed and first try to generate my project docs with:
phpdox -f phpdox.xml.dist

it saied:
[20.03.2015 - 16:33:27] The following file(s) had errors during processing and were excluded:
[20.03.2015 - 16:33:27]  - ..... /app.php (preg_replace_callback(): Compilation failed: support for \P, \p, and \X has not been compiled at offset 31)

any help is very appreciated, ths~

**Comment by theseer** [comment]
Your PCRE library has not been compiled with unicode properties support. This is a very old problem on CentOS / RHEL 5.x and probably other derivatives. I'll be adding a sanity check to the environment verification for that edge case.

You can find a more elaborate explanation as well as instructions on what can be done about it here:
https://chrisjean.com/unicode-support-on-centos-52-with-php-and-pcre/

**Comment by dogstarTest** [comment]
@theseer  thanks for your patience reply
