### ISSUE TITLE
@todo's

### ISSUE THREAD

**Issue by derekjkeller** [theseer/phpdox#215]
Hi,

Issue #6 mentions @todo handling was added, but #117 mentions it was later removed.

Is that still the case?

**Comment by theseer** [comment]
The only thing removed was the ToDo-List-Generator as it was broken and created only a text based output I didn't like at all.

@todo is still recognized and handled within the documentation, a new Report listing all todo annotations is under development.

**Comment by derekjkeller** [comment]
Awesome -- thanks!
