### ISSUE TITLE
vendor include at binary file

### ISSUE THREAD

**Issue by dehenne** [theseer/phpdox#226]
Hello,

Thanks for the awesome work.
But I have some troubles to run the phpdox file with:
https://github.com/theseer/phpdox/blob/master/phpdox#L46

```
$found = false;
foreach(array(__DIR__ . '/vendor', __DIR__ . '/../../../vendor') as $vendor) {
    if (file_exists($vendor)) {
        $found = true;
        require __DIR__ . '/src/vendor.php';
    }
}
```

should it not be so: ?

```
$found = false;
foreach(array(__DIR__ . '/vendor.php', __DIR__ . '/../../../vendor.php') as $vendor) {
    if (file_exists($vendor)) {
        $found = true;
        require __DIR__ . '/src/vendor.php';
    }
}
```

it works for me only so

 __DIR__ . '/vendor' does not work for me.

And I have a second question, why you use not $vendor as the require?

```
$found = false;
foreach(array(__DIR__ . '/vendor.php', __DIR__ . '/../../../vendor.php') as $vendor) {
    if (file_exists($vendor)) {
        $found = true;
        require $vendor;
    }
}
```

thank you in advance for your explanation :-)

**Comment by dehenne** [comment]
Ok, the fix is not correct. I made a very very bad fix for me.

```
foreach(array( __DIR__ . '/src/vendor', __DIR__ . '/../../../vendor') as $vendor) {
    if (file_exists($vendor.'.php')) {
        $found = true;
        $vendor = dirname(dirname(dirname(__FILE__)));
        require __DIR__ . '/src/vendor.php';
    }
}
```

to illustrate:
I use phpdox with the bin/phpdox from the composer installation. The execution is with phing.
the phing xml is:

```xml
<target name="phpdox" unless="phpdox.done" depends="phploc-ci,phpcs-ci,phpmd,phpunit" description="Generate project documentation using phpDox">
    <delete dir="${builddir}/docs"/>
    <exec command="${toolsdir}/phpdox -f ${project.basedir}/phpdox.xml" passthru="true"/>
  </target>
```

At the moment it works for. :-)

**Comment by theseer** [comment]
I have to admit, I neither get your change or the underlying issue.

**Comment by renanbr** [comment]
I'm not sure if I get what you said @dehenne, have you changed the [vendor directory config](https://getcomposer.org/doc/04-schema.md#config) in `composer.json` or the [COMPOSER_VENDOR_DIR](https://getcomposer.org/doc/03-cli.md#composer-vendor-dir) anyway?

... so maybe the problem is: phpdox always finds for standard vendor directory. If I got well the big picture, ignoring vendor directory name - like [this solution](https://github.com/sebastianbergmann/phpunit/blob/master/phpunit#L16) - could fix that.

**Comment by dehenne** [comment]
Sorry, if I have not expressed myself clearly.
The Problem is, i get the message "You need to set up the project dependencies...".
https://github.com/theseer/phpdox/blob/master/phpdox#L53

But all dependencies are installed.

@renanbr had the right idea :-) I change the name of my vendor dir.

@theseer 
I do not understand the following:

```
foreach(array(__DIR__ . '/vendor', __DIR__ . '/../../../vendor') as $vendor) {
```
Is vendor the "vendor" directory from composer or a directory from your src dir?
If vendor is the "vendor" directory from composer you should check the autoload.php file such as in PHPUnit.


thanks again for your help

**Comment by theseer** [comment]
Okay, I start to see the problem. And it indeed only exists due to the renamed the vendor directory.

I'll see how I can address that best.
Thank you for pointing that out!

**Comment by dehenne** [comment]
awesome. the fix works :+1: 
Thank you.
