### ISSUE TITLE
mkdir(): File exists

### ISSUE THREAD

**Issue by mhiran** [theseer/phpdox#228]
PHP Version: 5.4.16 (Linux)
PHPDox Version: 0.8.0-dev
ErrorException: E_WARNING
Location: /var/www/a1c-mhiran/checkout2/vendor/theseer/phpdox/src/generator/engine/AbstractEngine.php (Line 63)

mkdir(): File exists

#0 /var/www/a1c-mhiran/checkout2/vendor/theseer/phpdox/src/generator/engine/AbstractEngine.php(63): mkdir()
#1 /var/www/a1c-mhiran/checkout2/vendor/theseer/phpdox/src/generator/engine/html/Html.php(278): TheSeer\phpDox\Generator\Engine\AbstractEngine->saveDomDocument()
#2 /var/www/a1c-mhiran/checkout2/vendor/theseer/phpdox/src/generator/engine/html/Html.php(236): TheSeer\phpDox\Generator\Engine\Html->genericMethodBuild()
#3 unknown(0): TheSeer\phpDox\Generator\Engine\Html->buildClassMethod()
#4 /var/www/a1c-mhiran/checkout2/vendor/theseer/phpdox/src/generator/Generator.php(203): call_user_func()
#5 /var/www/a1c-mhiran/checkout2/vendor/theseer/phpdox/src/generator/Generator.php(294): TheSeer\phpDox\Generator\Generator->handleEvent()
#6 /var/www/a1c-mhiran/checkout2/vendor/theseer/phpdox/src/generator/Generator.php(249): TheSeer\phpDox\Generator\Generator->processClass()
#7 /var/www/a1c-mhiran/checkout2/vendor/theseer/phpdox/src/generator/Generator.php(142): TheSeer\phpDox\Generator\Generator->processWithNamespace()
#8 /var/www/a1c-mhiran/checkout2/vendor/theseer/phpdox/src/Application.php(241): TheSeer\phpDox\Generator\Generator->run()
#9 /var/www/a1c-mhiran/checkout2/vendor/theseer/phpdox/src/CLI.php(165): TheSeer\phpDox\Application->runGenerator()
#10 /var/www/a1c-mhiran/checkout2/vendor/theseer/phpdox/phpdox(68): TheSeer\phpDox\CLI->run()

**Comment by theseer** [comment]
Interesting this pops up again.
It has been reported before (Issue: #178) but vanished according to the original reporter.  I still don't understand how this can happen however. The failing mkdir() is only called if the [file_exists() check](https://github.com/theseer/phpdox/blob/1e88a45c51f75f31f44f66a131d820423563c93f/src/generator/engine/AbstractEngine.php#L62) returns false. So how can mkdir() after that claim it exists?

**Comment by mhiran** [comment]
I think it was my fault I had wrong path set to target.

Kind regards,
Manish Hiran
[Senior Software Developer]
[http://e.a1comms.co.uk/logo_a1_1.png]
Tel: 01773 549 554
[A1Comms Ltd. Contract House, Turnpike Business Park, Alfreton, Derbyshire DE55 7AD
Registered Company No. 04455131   VAT No. 797 0654 83]
A1 Comms<http://www.a1comms.co.uk/>
Buymobiles.net<http://www.buymobiles.net/>

**Comment by theseer** [comment]
Can you elaborate on that a bit more? If by any means possible I'd like to adjust the handling of such a situation so the reported crash does not occur.

**Comment by theseer** [comment]
Ping?

**Comment by mhiran** [comment]
Hi there,

I am getting following error:

[23.06.2015 - 13:39:23] Generator process completed
[23.06.2015 - 13:39:23] Processing project 'Checkout 2.0' completed.




Oups... phpDox encountered a problem and has terminated!

It most likely means you've found a bug, so please file a report for this
and paste the following details and the stacktrace (if given) along:

PHP Version: 5.4.16 (Linux)
PHPDox Version: 0.8.0-dev
ErrorException: E_COMPILE_ERROR
Location: /var/www/a1c-mhiran/checkout2/vendor/theseer/phpdox/src/vendor.php (Line 224)

{closure}(): Failed opening required '/var/www/a1c-mhiran/checkout2/vendor/theseer/phpdox/../../../vendor//phpunit/php-timer/PHP/Timer.php' (include_path='.:/usr/share/pear:/usr/share/php')

No stacktrace available

Kind regards,
Manish Hiran
[Senior Software Developer]
[http://e.a1comms.co.uk/logo_a1_1.png]
Tel: 01773 549 554
[A1Comms Ltd. Contract House, Turnpike Business Park, Alfreton, Derbyshire DE55 7AD
Registered Company No. 04455131   VAT No. 797 0654 83]
A1 Comms<http://www.a1comms.co.uk/>
Buymobiles.net<http://www.buymobiles.net/>

**Comment by theseer** [comment]
That's an unrelated issue (see #235).
Please focus on the mkdir() problem.

**Comment by theseer** [comment]
Can you provide some more feedback on the previous question?

**Comment by mhiran** [comment]
I had configured incorrectly in phpdox.xml.dist  

output path: I had set to "../www-root/build/", where "www-root" does not exists.

 And the following worked.

<?xml version="1.0" encoding="utf-8" ?>

<phpdox xmlns="http://xml.phpdox.net/config">
 <project name="Checkout 2.0" source="../checkout2/" workdir="/build/phpdox">
  <collector publiconly="false" backend="parser">
   <include mask="*.php" />
   <include mask="*.stub" />
   <exclude mask="**vendor**" />
   <inheritance resolve="true"/>
  </collector>

  <generator output="/build/">
  <enrich base="/build/logs">
    <source type="git" />
   </enrich>
   <build engine="html" enabled="true" output="api">
    <file extension="html" />
   </build>
  </generator>
 </project>
</phpdox>
