### ISSUE TITLE
native "callback" type is parsed as "object"

### ISSUE THREAD

**Issue by renanbr** [theseer/phpdox#233]
similar to https://github.com/theseer/phpdox/issues/232

---

`./phpdox.xml`

``` xml
<?xml version="1.0" encoding="utf-8" ?>
<phpdox xmlns="http://xml.phpdox.net/config">
    <project name="Example" source="${basedir}/src" workdir="${basedir}/build">
        <collector backend="parser" />
    </project>
</phpdox>
```

`./src/MyClass.php`

``` php
<?php

class MyClass
{
    /**
     * @var callback
     */
    public $callMe;
}
```

`./build/classes/MyClass.xml`

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<class xmlns="http://xml.phpdox.net/src" full="MyClass" namespace="" name="MyClass" abstract="false" final="false" start="3" end="9">
  <file path="/tmp/callback/src" file="MyClass.php" realpath="/tmp/callback/src/MyClass.php" size="83" time="2015-06-14T11:39:25+00:00" unixtime="1434281965" sha1="f41254dde6cfd6b9910270ca796004f45a7645a0" relative="MyClass.php"/>
  <member name="callMe" visibility="public" static="false" line="8">
    <docblock>
      <description/>
      <var type="object">
        <type full="callback" namespace="" name="callback"/>
      </var>
    </docblock>
  </member>
</class>
```

**Comment by theseer** [comment]
Actually, ```Callback``` is not a native type nor defined in any way within PHP.

There is a ```Callable``` type that can be used for type hinting and probably should be used in this case as well. I'll leave this bug open as the same problem exists.

**Comment by theseer** [comment]
Scrutinizer found an (Issue)[https://scrutinizer-ci.com/g/theseer/phpdox/inspections/31a9a5b4-42c2-4fad-b4a8-22bb2aafc1f9/issues/files/src/docblock/elements/VarElement.php?status=new&orderField=path&order=asc&honorSelectedPaths=0] after merging. 

@MacFJA Can you have a look at that?
