### ISSUE TITLE
paths for php-timer changed and break phpdoc

### ISSUE THREAD

**Issue by thomas-koch-comsolit** [theseer/phpdox#235]
I updated php-timer 1.0.5 to 1.0.6. The locations of the PHP class files changed and now phpdox outputs:

     [exec] Oups... phpDox encountered a problem and has terminated!
     [exec] 
     [exec] It most likely means you've found a bug, so please file a report for this
     [exec] and paste the following details and the stacktrace (if given) along:
     [exec] 
     [exec] PHP Version: 5.4.41-0+deb7u1 (Linux)
     [exec] PHPDox Version: 0.8.0-dev
     [exec] ErrorException: E_COMPILE_ERROR 
     [exec] Location: /var/lib/jenkins/workspace/kurad-review/vendor/theseer/phpdox/src/vendor.php (Line 224)
     [exec] 
     [exec] {closure}(): Failed opening required '/var/lib/jenkins/workspace/kurad-review/vendor/theseer/phpdox/../../../vendor//phpunit/php-timer/PHP/Timer.php' (include_path='.:/usr/share/php:/usr/share/pear')
     [exec] 
     [exec] No stacktrace available

**Comment by edvinasme** [comment]
could you release a 0.8.1 with this fix please?

**Comment by theseer** [comment]
Release is due tomorrow.
