### ISSUE TITLE
phpDox crash error

### ISSUE THREAD

**Issue by dstockto** [theseer/phpdox#237]
I don't know what else to provide than the message that said to file a report. The only change I made that I think may be relevant was upgrading phpunit/* and then running my build. Sorry for lack of information.

```
[exec] Oups... phpDox encountered a problem and has terminated!
     [exec]
     [exec] It most likely means you've found a bug, so please file a report for this
     [exec] and paste the following details and the stacktrace (if given) along:
     [exec]
     [exec] PHP Version: 5.5.8 (Linux)
     [exec] PHPDox Version: 0.8.1-dev
     [exec] ErrorException: E_COMPILE_ERROR
     [exec] Location: /vagrant_web/vendor/theseer/phpdox/src/vendor.php (Line 224)
     [exec]
     [exec] {closure}(): Failed opening required '/vagrant_web/vendor/theseer/phpdox/../..//phpunit/php-timer/PHP/Timer.php' (include_path='.:/usr/share/pear:/usr/share/php')
     [exec]
     [exec] No stacktrace available
```

**Comment by dstockto** [comment]
Never mind on this. I think you've fixed this. I was able to upgrade to the latest code and it's not happening any more.

**Comment by theseer** [comment]
Yeah, Sebastian changed the filesystem layout for PHP-Timer and I wasn't strict enough in the composer.json to pin it to a version my custom autoloader can work with.
