### ISSUE TITLE
PHP_Timer Not Found

### ISSUE THREAD

**Issue by sataris** [theseer/phpdox#238]
Oups... phpDox encountered a problem and has terminated!

It most likely means you've found a bug, so please file a report for this
and paste the following details and the stacktrace (if given) along:

PHP Version: 5.5.12-2ubuntu4.6 (Linux)
PHPDox Version: 0.8.1
ErrorException: E_ERROR 
Location: phar:///usr/local/bin/phpdox/phpdox/logger/ShellProgressLogger.php (Line 131)

Class 'PHP_Timer' not found

No stacktrace available

**Comment by theseer** [comment]
Fixed with 0.8.1.1.
