### ISSUE TITLE
phpDox failed while running

### ISSUE THREAD

**Issue by intekhabrizvi** [theseer/phpdox#239]
PHP Version: 5.5.14 (Darwin)
PHPDox Version: 0.8.0
ErrorException: E_ERROR 
Location: phar:///usr/local/bin/phpdox/vendor/nikic/php-parser/lib/PhpParser/Lexer.php (Line 54)

Allowed memory size of 134217728 bytes exhausted (tried to allocate 72 bytes)

No stacktrace available

**Comment by Eternal-Infinity** [comment]
I'd say you'd need to set up the value for the memory_limit in your php.ini.
So I wouldn't say this is a problem with phpdox.

**Comment by theseer** [comment]
Duplicate to #159
