### ISSUE TITLE
Real demo example ?

### ISSUE THREAD

**Issue by roukmoute** [theseer/phpdox#246]
hi,

You hace a demo section in your website.
But it's only a benchmark not a demo.
Could you add a real demo to see you documentation generator ?

Thanks

**Comment by Eternal-Infinity** [comment]
There is a demo on the website.
You can see a generated documentation for phpdox itself:

http://phpdox.de/demo/phpDox/index.xhtml

**Comment by theseer** [comment]
There are some other projects on the demo page. They all  have a demo HTML link.
If you want to see some other project, let me know and i'll consider adding it.
