### ISSUE TITLE
Feature-Request: SVN-Enricher

### ISSUE THREAD

**Issue by Eternal-Infinity** [theseer/phpdox#247]
At the beginning of the year I set up phpdox for my project.
Back then I saw there was a GIT enricher, but there seemed to be no SVN enricher.
(I **have to** use SVN, so....)

On your website I saw a text:

> Writing enricher plugins is easy and allows phpDox to process additional information from new tools quickly.

Is there a way to explain how to write an enricher plugin?
I could at least _try_ to write one for SVN, if there is not already one.
Don't know how much time I will have for this but it seems like a nice little project if there is some spare time for me ;)

**Comment by theseer** [comment]
I don't use SVN very much and do not have any projects other than the PHP Documentation that (still) uses it, thus I'm lagging a test project that makes sense for developing it. So yes, if you have some time to write an enricher for it, that would be awesome.

Creating a new Enricher should be simple. They basically add additional nodes into the generated XML for each unit (aka class, trait or interface), wrapped into a container. Depending on the interface your Enricher implements (and if it's enabled in the phpdox.xml configuration), your code will get called with Events, providing you with context information. It's up to you do decide what to do with such an event and how and what to add to the XML.

Technically, you can extend the AbstractEnricher that provides basically the helper method to get a container and implement the interface(s) you consider to need for your Enricher. 

There are various examples you could look at on how the logic works in the ```src/generator/enricher```. If you stumble upon any problems, let me know and I'll be happy to try to clarify things for you. This might actually lead to a very nice developer documentation ;)

**Comment by Eternal-Infinity** [comment]
Thank you for your kind reply
I will look into this, when I find the time for this.
Not promising it will be any soon, but this sounds pretty interesting to me and it would be a great way to finally contribute something myself to this awesome project (hoping this could be useful for someone else too)

**Comment by theseer** [comment]
I consider SVN dead. And since nothing happend here for almost 2 years, I'll close this.
