### ISSUE TITLE
missing class.xsl / please remove dependency on PEAR files

### ISSUE THREAD

**Issue by b7kich** [theseer/phpdox#249]
Running phpdox-0.8.1.1.phar 
...
     [exec] Exception: TheSeer\fDOM\fDOMException (Code: 1)
     [exec] Location: phar:///content/ticketing2/bin/phpdox-0.8.1.1.phar/vendor/theseer/fdomdocument/src/fDOMDocument.php (Line 144)
     [exec]
     [exec] loading file '/usr/share/pear/TheSeer/phpDox/templates/html/method.xsl' failed.
     [exec]
     [exec] [XML-STRING] [Line: 0 - Column: 0] Warning 1549: failed to load external entity "/usr/share/pear/TheSeer/phpDox/templates/html/method.xsl"
     [exec]
     [exec]
     [exec] #0 phar:///content/ticketing2/bin/phpdox-0.8.1.1.phar/phpdox/generator/engine/html/Html.php(115): TheSeer\phpDox\Generator\Engine\AbstractEngine->getXSLTProcessor()
     [exec] #1 phar:///content/ticketing2/bin/phpdox-0.8.1.1.phar/phpdox/generator/engine/html/Html.php(147): TheSeer\phpDox\Generator\Engine\Html->getXSLTProcessor()
     [exec] #2 unknown(0): TheSeer\phpDox\Generator\Engine\Html->buildStart()
     [exec] #3 phar:///content/ticketing2/bin/phpdox-0.8.1.1.phar/phpdox/generator/Generator.php(203): call_user_func()
     [exec] #4 phar:///content/ticketing2/bin/phpdox-0.8.1.1.phar/phpdox/generator/Generator.php(140): TheSeer\phpDox\Generator\Generator->handleEvent()
     [exec] #5 phar:///content/ticketing2/bin/phpdox-0.8.1.1.phar/phpdox/Application.php(241): TheSeer\phpDox\Generator\Generator->run()
     [exec] #6 phar:///content/ticketing2/bin/phpdox-0.8.1.1.phar/phpdox/CLI.php(165): TheSeer\phpDox\Application->runGenerator()
     [exec] #7 /content/ticketing2/bin/phpdox-0.8.1.1.phar(451): TheSeer\phpDox\CLI->run()
     [exec]
     [exec]
     [exec]
     [exec]
     [exec]
     [exec] Oups... phpDox encountered a problem and has terminated!
     [exec]
     [exec] It most likely means you've found a bug, so please file a report for this
     [exec] and paste the following details and the stacktrace (if given) along:
     [exec]
     [exec] PHP Version: 5.5.12 (Linux)
     [exec] PHPDox Version: 0.8.1.1
     [exec] ErrorException: E_CORE_WARNING
     [exec] Location: Unknown (Line 0)
     [exec]

**Comment by b7kich** [comment]
uninstalled the older PEAR phpdox I found on this box and getting missing class.xxl now

PHP Version: 5.5.12 (Linux)
PHPDox Version: 0.8.2-dev
Exception: TheSeer\fDOM\fDOMException (Code: 1)
Location: /content/ticketing2/vendor/theseer/fdomdocument/src/fDOMDocument.php (Line 144)

loading file '/usr/share/pear/TheSeer/phpDox/templates/html/class.xsl' failed.

[XML-STRING] [Line: 0 - Column: 0] Warning 1549: failed to load external entity "/usr/share/pear/TheSeer/phpDox/templates/html/class.xsl"


#0 /content/ticketing2/vendor/theseer/phpdox/src/generator/engine/html/Html.php(115): TheSeer\phpDox\Generator\Engine\AbstractEngine->getXSLTProcessor()
#1 /content/ticketing2/vendor/theseer/phpdox/src/generator/engine/html/Html.php(141): TheSeer\phpDox\Generator\Engine\Html->getXSLTProcessor()
#2 unknown(0): TheSeer\phpDox\Generator\Engine\Html->buildStart()
#3 /content/ticketing2/vendor/theseer/phpdox/src/generator/Generator.php(203): call_user_func()
#4 /content/ticketing2/vendor/theseer/phpdox/src/generator/Generator.php(140): TheSeer\phpDox\Generator\Generator->handleEvent()
#5 /content/ticketing2/vendor/theseer/phpdox/src/Application.php(241): TheSeer\phpDox\Generator\Generator->run()
#6 /content/ticketing2/vendor/theseer/phpdox/src/CLI.php(165): TheSeer\phpDox\Application->runGenerator()
#7 /content/ticketing2/vendor/theseer/phpdox/phpdox(68): TheSeer\phpDox\CLI->run()

**Comment by theseer** [comment]
The phar archive is fully self-contained, no need to have any pear component installed.
Can you paste the generator-part of the phpdox.xml config file?

My assumption would be that you have a template path for the html engine configured which is invalid.

**Comment by b7kich** [comment]
Oh - my bad. You're right. Sorry to hassle you and thanks for responding!

        <generator output="build/api">
            
            <build engine="html" enabled="true" output="html">
                <template dir="/usr/share/pear/TheSeer/phpDox/templates/html" />
            </build>
