### ISSUE TITLE
PHPDox runs successfully, enrichers do nothing (except phploc) on my Windows machine

### ISSUE THREAD

**Issue by izanev** [theseer/phpdox#254]
## The Story

I have recently decided to run with PHPDox. I found that it supports various enrichers and I was happy to use them in my project. I have activated the following enrichers for my project: build, phploc, pmd, phpcs, git, phpunit.

When I run phpdox from the command line, everything is smooth and the tool completes without any errors. When I go to the documentation, in the "Overview" tab I can see phploc analysis. When I open a class I cannot see any enrichment.

I'm running Windows 10.

I got really curious and decided to investigate phpdox further...here's what I found.

## Issue 1: Windows Path Separator

The path separator on Windows is backslash, while on unix it is forward slash. The problem lies in the "FileInfo" class, method "getRealPath". This method uses return "$this->toUnix($path);" which transforms the path into a Unix-style forward slash path. The problem, however, is that when I run "phpmd" to generate me the xml report, it uses the proper backslash for Windows. It turns out that the PHPMD enricher (and other enrichers as well) use the file path to check if there is "findings" for a certain file. No findings will be available due to the path difference. When I removed "$this->toUnix($path)" PHPMD and PHPUnit coverage started working!

## Issue 2: PHPCS - private $findings should be protected

This problem took me a while. The PHPCS enricher extends CheckStyle. The problem is that both of them keep a "private $findings" variable. Which means that CheckStyle parent class would not have access to any findings that PHPCS has obtained. I managed to fix that by setting both $findings variables in CheckStyle and PHPCS enrichers to be "protected".

## Issue 3: Git dirty flag not working on my machine

I investigated the Git Enricher and figured out it executes the following command to check if git repo is available: "git describe --always --dirty 2" (located in the enrichStart method of Git.php). The problem is that when I executed this command on my repository, it says the following thing: "fatal: --dirty is incompatible with commit-ishes". I'm not a git-pro, so I decided to remove "--dirty 2" and it fixed the problem.

I'm not sure if my fixes are correct because I don't know the scope of the project and whether my fixes will break something else. I decided to share anyway, if someone else encounters the same problem.

P.S. PhpDox code has been written really nice and clean, I managed to get into it really quickly!

**Comment by theseer** [comment]
Thank you for researching the issue and all your findings.

## Issue 1: Windows Path Selector
Did I mention before that I can't stand windows? I guess I have to adjust the enricher loader code to translate the path's to unix format. That's a good catch and should have been done from the beginning. Removing the toUnix calls is likely to cause more harm than good in the long run as I do *not* intend to deal with the broken windows variants or have constant switches.

## Issue 2: PHPCS
I'm still not sure why there are two enricher for something that technically is almost identical.  The differences between the two formats are almost none-existent. But your issue looks like a duplicate  issue #236.

@exi Any update on this?

## Issue 3: GIT describe
That's actually a very bizarre issue as it's not supposed to be a "--dirty 2" but rather "--dirty" followed by a redirection of STDERR to /dev/null or NUL for windows. I can see that "--dirty 2" would cause the aforementioned error message if the "2" is interpreted as a specifier for a commit hash.

But that's wrong, and not logical as the cli call in https://github.com/theseer/phpdox/blob/master/src/generator/enricher/git/Git.php#L71 clearly pipes the output of STDERR (aka FileDescriptor 2) to NUL. I don't see how the exec call could get mangled up here...

**Comment by izanev** [comment]
Hello, regarding third issue: funny thing is when I execute with the 2>NUL it creates a NUL file in the directory. When I execute with "2>nul" it works okay in my command prompt. Do you think that case sensitivity might be the issue here?

**Comment by theseer** [comment]
It almost looks like it. I'm quite sure I saw an example on msdn with uppercase - but fail to find it and all other examples use a lowercase nul.
Thank's for pointing that out. I'll update the code asap.

**Comment by theseer** [comment]
## Issue 1
Should be fixed - tracking otherwise continues in #250

## Issue 2
PHPCS enricher is subject to major refactoring. Tracked in #236

## Issue 3
As no further problems got reported, I consider this fixed.
