### ISSUE TITLE
Relax requirement constraints for nikic/php-parser

### ISSUE THREAD

**Issue by mostwanted1976** [theseer/phpdox#256]
Phpdox's `composer.json` requires `nikic/php-parser` in version `=1.3.0`. This can easily conflict with other package's requirements: e.g. https://github.com/sstalle/php7cc which requires version `~1.4`.

It would be great if `phpdox` was compatible with version `1.4` of `nikic/php-parser`. Maybe the requirements could in this case be set more relaxed: e.g. `^1.3.0` or `>=1.3.0 <1.5`.

**Comment by theseer** [comment]
My development version locally already uses php-parser in version 1.4.0.
I'll have a look at it and try to push the update asap.

**Comment by theseer** [comment]
PHP-Parser has been upgraded to 2.0.0.
