### ISSUE TITLE
Installation Error Timezone not detecting

### ISSUE THREAD

**Issue by webkingashu** [theseer/phpdox#258]
After install when i run 
phpdox --version

or nay other command, it keep giving me the following error 

```
PHP Version: 5.5.30 (Linux)
PHPDox Version: 0.8.0
ErrorException: E_WARNING
Location: phar:///usr/bin/phpdox/phpdox/shared/Version.php (Line 71)

date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone.

#0 phar:///usr/bin/phpdox/phpdox/shared/Version.php(71): date()
#1 phar:///usr/bin/phpdox/phpdox/CLI.php(216): TheSeer\phpDox\Version->getInfoString()
#2 phar:///usr/bin/phpdox/phpdox/CLI.php(175): TheSeer\phpDox\CLI->showVersion()
#3 /usr/bin/phpdox(450): TheSeer\phpDox\CLI->run()
```

However timezone is already set, when i run command  

date

it gives me local date time.

What is the issue ??

**Comment by theseer** [comment]
The error message shown is about your *PHP* environment, not necessarily your system in general. Check your php.ini file for the date.timezone setting and adjust it accordingly.

But you are using an outdated version of phpDox anyway, the code of 8.1.1 already got changed to set a default (UTC, as recommended by the error message) to avoid this error message. Please note that this change *hides* the error only.

**Comment by webkingashu** [comment]
got that. Warning can be ignored

I got it working by running directly as 
```
php phdox.phar  --skel

``
