### ISSUE TITLE
PHP7 ErrorException while running phpdox command

### ISSUE THREAD

**Issue by matiangul** [theseer/phpdox#274]
```
./vendor/bin/phpdox --skel > phpdox.xml.dist
./vendor/bin/phpdox
```

...
Version: a58c4c5-dirty
Exception: ErrorException
Location: /home/vagrant/Projekty/officewise_middleware/vendor/theseer/phpdox/src/shared/ErrorHandler.php (Line 115)

Uncaught TypeError: Argument 1 passed to TheSeer\phpDox\ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /home/vagrant/Projekty/officewise_middleware/vendor/theseer/phpdox/src/shared/ErrorHandler.php:115
Stack trace:
#0 [internal function]: TheSeer\phpDox\ErrorHandler->handleException(Object(Error))
#1 {main}
  thrown

**Comment by theseer** [comment]
Fixed with 29f8bb8ca0c69d35947c734533d151fc84c955f5 and part of the 0.9.0 release.
