### ISSUE TITLE
Allowed memory size of 134217728 bytes exhausted (tried to allocate 8969530 bytes)

### ISSUE THREAD

**Issue by simonrenger** [theseer/phpdox#275]
Oups... phpDox encountered a problem and has terminated!

It most likely means you've found a bug, so please file a report for this
and paste the following details and the stacktrace (if given) along:

PHP Version: 5.6.21 (Linux)
PHPDox Version: 0.8.1.1
ErrorException: E_ERROR 
Location: phar:///usr/local/bin/phpdox/vendor/nikic/php-parser/lib/PhpParser/Lexer/Emulative.php (Line 95)

Allowed memory size of 134217728 bytes exhausted (tried to allocate 8969530 bytes)

No stacktrace available

**Comment by theseer** [comment]
This is not a bug.
Your PHP process ran out of memory.

**Comment by simonrenger** [comment]
Sorry realised this afterwards had only no internet to change it :P I am
sorry but I might found a bug but I have to run son test and if it's a bug
I'll report it. (This potential bug has to do with memory or better an
endless loop)
Am 16.06.2016 20:20 schrieb "Arne Blankerts" <notifications@github.com>:
