### ISSUE TITLE
failed to load external entities

### ISSUE THREAD

**Issue by mattwebdev** [theseer/phpdox#281]
....I/O warning : failed to load external entity "phar://phpdox.phar/templates/html/components.xsl"
I/O warning : failed to load external entity "phar://phpdox.phar/templates/html/functions.xsl"
I/O warning : failed to load external entity "phar://phpdox.phar/templates/html/synopsis.xsl"

Oups... phpDox encountered a problem and has terminated!

It most likely means you've found a bug, so please file a report for this
and paste the following details and the stacktrace (if given) along:

PHP Version: 5.6.22 (Darwin)
PHPDox Version: 0.8.1.1
ErrorException: E_WARNING 

Location: phar:///Users/.../Sites/.../phpdox.phar/vendor/theseer/fxsl/src/fxsltprocessor.php (Line 192)

XSLTProcessor::transformToDoc(): No stylesheet associated to this object

#0 phar:///Users/.../Sites/.../phpdox.phar/vendor/theseer/fxsl/src/fxsltprocessor.php(192): XSLTProcessor->transformToDoc()

#1 phar:///Users/.../Sites/.../phpdox.phar/phpdox/generator/engine/html/Html.php(208): TheSeer\fXSL\fXSLTProcessor->transformToDoc()

#2 unknown(0): TheSeer\phpDox\Generator\Engine\Html->buildClass()

#3 phar:///Users/.../Sites/.../phpdox.phar/phpdox/generator/Generator.php(203): call_user_func()

#4 phar:///Users/.../Sites/.../phpdox.phar/phpdox/generator/Generator.php(277): TheSeer\phpDox\Generator\Generator->handleEvent()

#5 phar:///Users/.../Sites/.../phpdox.phar/phpdox/generator/Generator.php(249): TheSeer\phpDox\Generator\Generator->processClass()

#6 phar:///Users/.../Sites/.../phpdox.phar/phpdox/generator/Generator.php(142): TheSeer\phpDox\Generator\Generator->processWithNamespace()

#7 phar:///Users/.../Sites/.../phpdox.phar/phpdox/Application.php(241): TheSeer\phpDox\Generator\Generator->run()

#8 phar:///Users/.../Sites/.../phpdox.phar/phpdox/CLI.php(165): TheSeer\phpDox\Application->runGenerator()

#9 /Users/.../Sites/.../phpdox.phar(451): TheSeer\phpDox\CLI->run()

**Comment by theseer** [comment]
Duplicate to #255
