### ISSUE TITLE
New "official" release

### ISSUE THREAD

**Issue by DannyvdSluijs** [theseer/phpdox#283]
Can there be a new "official" release of the phpdox project? As the latest version is over one year old (0.8.1.1 dated July '15). And is pre PHP7 era, causing issues with outdated dependancies (nikic/php-parser which has no support for PHP7).

**Comment by DannyvdSluijs** [comment]
If there is any help need let us (the community) know, and we can assist where needed.

**Comment by theseer** [comment]
Thanks for the reminder and thank you for offering help.
I certainly need to spent more time on phpDox again and particularly give the template output some love.
