### ISSUE TITLE
Error in Generator

### ISSUE THREAD

**Issue by Khorsa** [theseer/phpdox#284]
Generator has an error of public/private/protection attribute detection in files: 
\src\generator\project\objects\MethodObject.php
\src\generator\project\objects\MemberObject.php

```
    public function isPublic() {
        return $this->node->getAttribute('visibility', 'public') == 'public';
    }
    public function isPrivate() {
        return $this->node->getAttribute('visibility', 'public') == 'private';
    }
    public function isProtected() {
        return $this->node->getAttribute('visibility', 'public') == 'protected';
    }
```

**Comment by theseer** [comment]
Nice Catch. Thank you!

**Comment by theseer** [comment]
Actually, this was not a bug. The detection logic is correct.

**Comment by theseer** [comment]
For clarification: The "public" in the getAttribute() is the *default* in case the attribute is not set. That's correct, since PHP by default considers things public.

**Comment by Khorsa** [comment]
Yes, i'm sorry - it was wrong place for error ))
May be, it is here:

Application.php [236]:
            $generator->run(
                new \TheSeer\phpDox\Generator\Project(
                    $srcDir,
                    $pconfig->getWorkDirectory()
                )
            );

Generator.php [135]:
       public function run(Project $project, $publicOnly = FALSE) {

($publicOnly == TRUE) will never recieve by Generator from Application

**Comment by theseer** [comment]
That indeed looks more like a problem.
