### ISSUE TITLE
Unable to set a filename for PHPUnit coverage xml file

### ISSUE THREAD

**Issue by Starli0n** [theseer/phpdox#285]
Hi, 

Contrary to the other enrichment, it seems that it is impossible to set a specific file name for the coverage xml file of PHPUnit.

I have a generated file from PHPUnit like

 `${basedir}/report/build/clover.xml`

And I thought to configure `phpdox` like this:

````xml
<enrich base="${basedir}/report/build">
    <!-- PHPUnit Coverage XML -->
    <source type="phpunit">
        <file name="clover.xml" />
    </source>
````

But it seems that it does not work and I am obliged to rename the file like that 

`${basedir}/report/build/clover/index.xml`

````xml
    <!-- PHPUnit Coverage XML -->
    <source type="phpunit">
        <coverage path="clover" />
    </source>
````

Did I have missed something ?

**Comment by theseer** [comment]
You're using the wrong coverage format for phpDox.
For phpDox' coverage enricher, more details are needed than the clover format provides.

Please configure PHPUnit to generate its own coverage xml report (```<log type="coverage-xml" target="/same/path/as/in/phpdox.xml" />```).

Other than that, this is a duplicate for #250

**Comment by Starli0n** [comment]
I am sorry, I came across that issue but I did not read carefully.

However, now that I have defined a coverage folder, I can see that the xml files corresponding to my classes are generated but they are not taken into account in `phpDox`

I have in the log

`Enricher PHPUnit Coverage XML initialized successfully`

When I open the `classes.xhtml` I can see `EMPTY` instead of `PASSED` whereas I have 100% of test coverage on my (little) project.

My configuration is :

````xml
    <!-- PHPUnit Coverage XML -->
    <source type="phpunit">
        <coverage path="coverage" />
        <filter directory="${basedir}/test" />
    </source>
````

My PHPUnit config is in `${basedir}/test/phpunit.xml` for the whitelist

````xml
<?xml version="1.0" encoding="UTF-8"?>

<phpunit colors="true">
    <testsuites>
        <testsuite name="boilerplatedownloader">
            <directory suffix="Test.php">../test</directory>
        </testsuite>
    </testsuites>
    <filter>
        <whitelist processUncoveredFilesFromWhitelist="true">
            <directory suffix=".php">../src/api</directory>
        </whitelist>
        <blacklist>
            <directory suffix=".php">../public</directory>
            <directory suffix=".php">../publish</directory>
            <directory suffix=".php">../boilerplatedownloader</directory>
        </blacklist>
    </filter>
</phpunit>
````

I tried to `phpunit.xml` to `phpunit.xml.dist`, to put it in the root but I had always a `EMPTY` tag


Do you know why ?

Thank you for your help

**Comment by theseer** [comment]
What OS are you running under?

**Comment by Starli0n** [comment]
Windows 7

**Comment by theseer** [comment]
Looks like that might be the Point 2 of #254 for you.
I'll try to finally come up with a solution for that tomorrow.

**Comment by theseer** [comment]
I just pushed a few changes that should fix this issue.

Please verify and report back.

**Comment by Starli0n** [comment]
I am not able to build properly on Windows but if you can provide me with a phar file, I would be glad to test.

In the meantime, I tried to figure out the issue and I replaced the `\` windows style path by '/' in the xml files and it works well.

I think you have to include a way to parse windows file from the various xml files.
