### ISSUE TITLE
Composer showing (or installing) old version? 

### ISSUE THREAD

**Issue by sataris** [theseer/phpdox#297]
I'm not sure what's going on here, phpdox is installed globally (via composer)

Composer installs 0.9.0 but phpdox shows as 0.8.2-dev

`which phpdox`
`/home/removed/.composer/vendor/bin/phpdox`

`composer show | grep phpdox`
`theseer/phpdox                     0.9.0  A fast Documentation generator fo`

`phpdox --version`
`phpDox 0.8.2-dev - Copyright (C) 2010 - 2016 by Arne Blankerts`

**Comment by theseer** [comment]
Composer is correct.
I forgot to adjust the version information when tagging the 0.9.0 release.
