### ISSUE TITLE
didn't touch the folder

### ISSUE THREAD

**Issue by REZ1DENT3** [theseer/phpdox#303]
hello. how to tell that phpdox didn't touch the folder?

**Comment by theseer** [comment]
??

**Comment by REZ1DENT3** [comment]
I have directory. 
 src/App1
 src/App2
 src/App3
 src/App
 src/Bar
 src/Foo 

I need documentation on "app1", "app2", "app3" one configuration.

filter path. 
Example 
excluded paths: src/App, src/Bar, src/Foo
