### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by johnrobertporter** [theseer/phpdox#306]
Where is the config documentation to explain how to use coverage and other methods of enrichment?

You mention it on your homepage, but then have no explanation on how to do it.

**Comment by theseer** [comment]
I admit that documentation is quite spark but the example configuration file (``--skel``) is annotated and should get you started.

**Comment by johnrobertporter** [comment]
Thanks for pointing that out! I missed that completely.

**Comment by theseer** [comment]
Glad it helped. If you any further issues, let me know.

I'll close this ticket for now.
