### ISSUE TITLE
Gearman + phpDox

### ISSUE THREAD

**Issue by daerimin** [theseer/phpdox#314]
I already have Gearman running for other things on this server, and it seems to be breaking phpDox:

```
[root@us-east-1 ~]# ./phpdox-0.10.1.phar --version
phpDox 0.10.1 - Copyright (C) 2010 - 2017 by Arne Blankerts and Contributors



Oups... phpDox encountered a problem and has terminated!

It most likely means you've found a bug, so please file a report for this
and paste the following details and the stacktrace (if given) along:

PHP Version: 5.6.32 (Linux)
PHPDox Version: 0.10.1
ErrorException: E_CORE_WARNING 
Location: Unknown (Line 0)

Module 'gearman' already loaded

No stacktrace available

```

**Comment by theseer** [comment]
The shown error message suggest that your environment tries to load the extension "gearman" twice. Since phpDox has a very strict error handling, the problem - of type E_CORE_WARNING - get's translated into an exception which in turn leads to the termination of the process.

I'd assume that having a simple executable php script would lead to the same error:
```php
#!/bin/env php
<?php
echo "Hello world.\n";
```

**Comment by daerimin** [comment]
Thank you for your reply.  I have tested as requested, no errors.  This is an active server with hundreds of PHP scripts, some which use Gearman, most do not.  The Gearman process is running in the background waiting for jobs from the application.  I don't know if this is the issue, or if something else is going on.  I'm happy to do any other testing you'd like.

```
[root@us-east-1 ]# more test.php 
#!/bin/env php
<?php
echo "Hello world.\n";
[root@us-east-1 ]# 
[root@us-east-1 ]# 
[root@us-east-1 ]# php test.php 
Hello world.
[root@us-east-1 ]# 
```

**Comment by theseer** [comment]
Interesting.
How about:

```php
#!/bin/env php
<?php
set_error_handler(function(){ var_dump(func_get_args()); die('error caught'); });

echo "Hello world\n";
```

**Comment by theseer** [comment]
Okay, disregard that. It's an E_CORE_WARNING, the error handler won't see that.

**Comment by theseer** [comment]
The shutdown handler should catch it:

```php
#!/bin/env php
<?php
register_shutdown_function(function(){ $error=error_get_last(); if (!empty($error)) { var_dump($error); } });
echo "Hello world\n";
```

**Comment by theseer** [comment]
Ping? ;-)

**Comment by theseer** [comment]
No Feedback provided.
