### ISSUE TITLE
count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by samoilenko** [theseer/phpdox#321]
[phpdox] Oups... phpDox encountered a problem and has terminated!
   [phpdox]
   [phpdox] It most likely means you've found a bug, so please file a report for this
   [phpdox] and paste the following details and the stacktrace (if given) along:
   [phpdox]
   [phpdox] PHP Version: 7.2.0 (Linux)
   [phpdox] PHPDox Version: 0.11.0-dev
   [phpdox] ErrorException: E_WARNING
   [phpdox] Location: /project/api/vendor/theseer/phpdox/src/shared/FileInfoCollection.php (Line 67)
   [phpdox]
   [phpdox] count(): Parameter must be an array or an object that implements Countable
   [phpdox]
   [phpdox] #0 /project/api/vendor/theseer/phpdox/src/shared/FileInfoCollection.php(67): count()
   [phpdox] #1 /project/api/vendor/theseer/phpdox/src/shared/FileInfoCollection.php(53): TheSeer\phpDox\FileInfoCollection->count()
   [phpdox] #2 /project/api/vendor/theseer/phpdox/src/bootstrap/Bootstrap.php(56): TheSeer\phpDox\FileInfoCollection->valid()
   [phpdox] #3 /project/api/vendor/theseer/phpdox/src/CLI.php(130): TheSeer\phpDox\Bootstrap->load()
   [phpdox] #4 /project/api/vendor/theseer/phpdox/phpdox(67): TheSeer\phpDox\CLI->run()
   [phpdox]
   [phpdox]
   [phpdox]
   [phpdox] Result: 5

**Comment by theseer** [comment]
Duplicate #315
