### ISSUE TITLE
Issue in version 0.11.0

### ISSUE THREAD

**Issue by acharyajay007** [theseer/phpdox#324]
It most likely means you've found a bug, so please file a report for this
and paste the following details and the stacktrace (if given) along:

PHP Version: 5.6.12 (WINNT)
PHPDox Version: 0.11.0-dev
ErrorException: E_ERROR
Location: W:\cleartax_jay\vendor\nikic\php-parser\lib\PhpParser\Lexer.php (Line 75)

Allowed memory size of 134217728 bytes exhausted (tried to allocate 36 bytes)

No stacktrace available

**Comment by theseer** [comment]
As the error message shows, PHP ran out of memory:

> Allowed memory size of 134217728 bytes exhausted (tried to allocate 36 bytes)

This does not seem like a bug to me, even though 128 MB should get you quite far it may not be enough for a large project. You might also want to upgrade to a recent PHP Version like 7.2.1.
