### ISSUE TITLE
when I run the phive install method, I get 10.1 rather than 11.0 

### ISSUE THREAD

**Issue by sunnysideup** [theseer/phpdox#327]
I want to install phpdox 11.0 on cd /usr/local/bin/phpdox ... how can I do that? THANK YOU

**Comment by theseer** [comment]
I can't confirm that:

```
theseer@nyda /tmp/test $ phive install phpdox
Phive 0.9.0 - Copyright (C) 2015-2018 by Arne Blankerts, Sebastian Heuer and Contributors
Fetching respository list
Downloading https://api.github.com/repos/theseer/phpdox/releases
Downloading https://github.com/theseer/phpdox/releases/download/0.11.0/phpdox-0.11.0.phar
Downloading https://github.com/theseer/phpdox/releases/download/0.11.0/phpdox-0.11.0.phar.asc
Linking /home/theseer/.phive/phars/phpdox-0.11.0.phar to /tmp/xxx/tools/phpdox
```

Also, invoking the test install works:

```
theseer@nyda /tmp/xxx $ ./tools/phpdox --version
phpDox 0.11.0 - Copyright (C) 2010 - 2018 by Arne Blankerts and Contributors
```
Which version of `phive` are you using? Maybe the repository data you have locally is outdated and, for whatever strange reason, didn't auto update. You can force an update via `phive update-repository-list`.

To install `phpdox` under `/usr` you need root privileges and either `-g`  or `-t /usr/local/bin`.
