### ISSUE TITLE
Bug? count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by ColonelBlimp** [theseer/phpdox#329]
`phpdox -f build/phpdox.xml`

phpDox 0.11.0-dev - Copyright (C) 2010 - 2018 by Arne Blankerts and Contributors

[14.03.2018 - 04:40:20] Using config file 'build/phpdox.xml'
[14.03.2018 - 04:40:20] Registered collector backend 'parser'
[14.03.2018 - 04:40:20] Registered enricher 'build'
[14.03.2018 - 04:40:20] Registered enricher 'git'
[14.03.2018 - 04:40:20] Registered enricher 'checkstyle'
[14.03.2018 - 04:40:20] Registered enricher 'phpcs'
[14.03.2018 - 04:40:20] Registered enricher 'pmd'
[14.03.2018 - 04:40:20] Registered enricher 'phpunit'
[14.03.2018 - 04:40:20] Registered enricher 'phploc'
[14.03.2018 - 04:40:20] Registered output engine 'xml'
[14.03.2018 - 04:40:20] Registered output engine 'html'

Oups... phpDox encountered a problem and has terminated!

It most likely means you've found a bug, so please file a report for this
and paste the following details and the stacktrace (if given) along:

PHP Version: 7.2.1 (WINNT)
PHPDox Version: 0.11.0-dev
ErrorException: E_WARNING
Location: C:\Users\username\AppData\Roaming\Composer\vendor\theseer\phpdox\src\shared\FileInfoCollection.php (Line 67)

count(): Parameter must be an array or an object that implements Countable

#0 C:\Users\username\AppData\Roaming\Composer\vendor\theseer\phpdox\src\shared\FileInfoCollection.php(67): count()
#1 C:\Users\username\AppData\Roaming\Composer\vendor\theseer\phpdox\src\shared\FileInfoCollection.php(53): TheSeer\phpDox\FileInfoCollection->count()
#2 C:\Users\username\AppData\Roaming\Composer\vendor\theseer\phpdox\src\bootstrap\Bootstrap.php(56): TheSeer\phpDox\FileInfoCollection->valid()
#3 C:\Users\username\AppData\Roaming\Composer\vendor\theseer\phpdox\src\CLI.php(130): TheSeer\phpDox\Bootstrap->load()
#4 C:\Users\username\AppData\Roaming\Composer\vendor\theseer\phpdox\phpdox(79): TheSeer\phpDox\CLI->run()

**Comment by theseer** [comment]
I cannot reproduce this in any way. Also, the line numbers seem to be off.

Can you provide a simple testcase for this?

**Comment by ColonelBlimp** [comment]
I will try to do this ASAP as I think it is still failing in my build script.

**Comment by theseer** [comment]
No worries. I just fail to see how that can happen to begin with and have not managed to trigger this as of yet. But obviously there has to be a way ;)

**Comment by ColonelBlimp** [comment]
I can currently reproduce the issue, BUT I have phpdox globally on my dev machine, but it looks like there is a issue with some of packages from composer.  Let me re-install composer and test again.

**Comment by ColonelBlimp** [comment]
Close this issue.  I cleared out every global package from Composer and reinstalled the packages.  PhpDox now works just fine..,

**Comment by theseer** [comment]
Okay. Thanks for the effort anyhow.
