### ISSUE TITLE
Wrong namspace - not a PHPUnit code coverage file

### ISSUE THREAD

**Issue by cyrilverloop** [theseer/phpdox#333]
Hi,

When i use phpdox with a phpunit enricher, an exception is thrown saying "Wrong namspace - not a PHPUnit code coverage file" .

The file "src/generator/enricher/phpunit/PHPUnit.php" has a XMLNS constant which defined a "http" address. But phpunit generates xml report with a "http**s**" value. Hence the exception.

I tried modifying the phpunit report to "http" and the enricher stop throwing the exception.
I don't know if adding "http**s**" to the constant would have another impact.

php : 7.2.5
phpunit : 7.1.5
phpdox : 0.11.1

**Comment by theseer** [comment]
@sebastianbergmann Any Change I should have known about?

**Comment by theseer** [comment]
Found it: https://github.com/sebastianbergmann/php-code-coverage/commit/83f09c29758c52e71bdb81ad2cc9124b85b5a4ef

**Comment by cyrilverloop** [comment]
Thanks for the fix. I'm looking forward for the next release.

**Comment by joaomfrebelo** [comment]
Hi, the https://schema.phpunit.de/coverage/1.0 is returning error 404 nad because of that is not possible to use it. are nay other option to avoid this?

**Comment by theseer** [comment]
@joaomfrebelo I don't understand your problem? It's a __namespace__ uri, not a schema validation. (See https://github.com/theseer/phpdox/issues/367#issuecomment-514689771)

**Comment by theseer** [comment]
@joaomfrebelo If you think the fact the namespace uri doesn't resolve is a problem/bug, open an issue with https://github.com/sebastianbergmann/php-code-coverage
