### ISSUE TITLE
unable to install phpdox using composer

### ISSUE THREAD

**Issue by punramesh** [theseer/phpdox#339]
Command:
composer global require theseer/phpdox

Error message:
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for theseer/phpdox ^0.11.2 -> satisfiable by theseer/phpdox[0.11.2].
    - Conclusion: remove phpunit/php-timer 2.0.0
    - Conclusion: don't install phpunit/php-timer 2.0.0
    - theseer/phpdox 0.11.2 requires phpunit/php-timer ^1.0 -> satisfiable by phpunit/php-timer[1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9].
    - Can only install one of: phpunit/php-timer[1.0.3, 2.0.0].
    - Can only install one of: phpunit/php-timer[1.0.4, 2.0.0].
    - Can only install one of: phpunit/php-timer[1.0.5, 2.0.0].
    - Can only install one of: phpunit/php-timer[1.0.6, 2.0.0].
    - Can only install one of: phpunit/php-timer[1.0.7, 2.0.0].
    - Can only install one of: phpunit/php-timer[1.0.8, 2.0.0].
    - Can only install one of: phpunit/php-timer[1.0.9, 2.0.0].
    - Installation request for phpunit/php-timer (locked at 2.0.0) -> satisfiable by phpunit/php-timer[2.0.0].

Installation failed, reverting ./composer.json to its original content.

**Comment by theseer** [comment]
See https://github.com/theseer/phpdox/issues/328#issuecomment-372602708
