### ISSUE TITLE
Update dependencies (like php-timer)

### ISSUE THREAD

**Issue by michakrapp** [theseer/phpdox#349]
In your comment on https://github.com/theseer/phpdox/issues/328#issuecomment-372602708 you stated:
> my goal is to support every PHP-Version that at least still gets security fixes from the PHP Project

Since PHP 5.6 (and 7.0) recently reached their [EOL dates](http://php.net/eol.php) maybe you can update these dependencies like php-timer now?

I had the same problem, that my project already using php-timer v2.x and so I'm unable to install phpdox via composer

**Comment by theseer** [comment]
Done with commit 242a026a16492fb77a2af957a3747b105c68382a

**Comment by michakrapp** [comment]
Thanks.
So it will come with v0.12 right?

**Comment by theseer** [comment]
Yes.
