### ISSUE TITLE
Git version comparison bug in macOS

### ISSUE THREAD

**Issue by inash** [theseer/phpdox#381]
https://github.com/theseer/phpdox/blob/3945e2d5f4298725688965baa0d79741f882eff2/src/generator/enricher/git/Git.php#L349

Git on macOS has an additional word in the version line which happens to be wrongly picked up to compare in method `ensureGitVersionSupported`. Instead of picking up `2.20.1`, `Git-117)` is being picked up. Below is comparison of the git version string from different operating systems.

- Linux: git version 2.20.1
- Windows: git version 2.22.0.windows.1
- macOS: git version 2.20.1 (Apple Git-117)

Instead of `array_pop($parts)`, taking `$parts[2]` should be correct.

**Comment by wkejqb** [comment]
https://github.com/theseer/phpdox/pull/385 my MR should fix this.

**Comment by theseer** [comment]
I'm not fully sure the implementation in PR #385 is the best yet, but it certainly will fix things.

Good enough for now and thus merged.
