### ISSUE TITLE
Interface implementors

### ISSUE THREAD

**Issue by wkejqb** [theseer/phpdox#386]
Say, I have a class that implements some interface. I have link to the interface in class doc, but interface doc does not contain links to its implementations. I find it useful to have such links.
I might implement it myself, any guidance is appreciated.

**Comment by theseer** [comment]
I'm not sure I understand what you are looking for here?

phpDox should detect interfaces and implementors already. And it should reference them accordingly as long as the definition is part of the source code. E.g. an interface container should have list of all implementations found by phpDox.

What it's not seeing obviously would be any implementation that is NOT part of the current code base. Is that what you are looking for?

**Comment by wkejqb** [comment]
Thanks, probably code base was the issue here. Will close.
