### ISSUE TITLE
Uncaught Error: Cannot use object of type stdClass as array

### ISSUE THREAD

**Issue by mphilipps** [theseer/phpdox#390]
hi,
Usually we download the latest phpdox from **http://phpdox.de/releases/phpdox.phar**. However recently instead of the expected phar file/redirect to github we often get 260 bytes of php stack trace as a http 200 response.

```
<br />
<b>Fatal error</b>:  Uncaught Error: Cannot use object of type stdClass as array in /webspace/theseer/phpdox.net/www/php/redirect.php:16
Stack trace:
#0 {main}
  thrown in <b>/webspace/theseer/phpdox.net/www/php/redirect.php</b> on line <b>16</b><br />
```

Something is seriously broken with your webspace.

**Comment by theseer** [comment]
Thanks! Fixed.
