### ISSUE TITLE
Trait aliases are ignored

### ISSUE THREAD

**Issue by davidsneighbour** [theseer/phpdox#393]
The following code:

```
class Dropdowns extends Menus
{
    use MenuTrait {
        getToplevelItem as public get;
        setToplevelItem as public set;
    }
}
```

results in neither the trait methods (getToplevelItem/setToplevelItem) nor the get/set alias being documented in the documenation of the Dropdowns class. I would expect two public methods in the Dropdowns class documentation? They are private in the trait itself, but `as public` works as expected under 7.4 (the methods are public accessible).

**Comment by theseer** [comment]
As the subject states: It's ignored because there is literally no code taking care of that construct as of yet.

I'll try to add it but it can take some time.
