### ISSUE TITLE
Generates plain list of properties and methods. No annotations

### ISSUE THREAD

**Issue by nzurita** [theseer/phpdox#396]
When generating `phpdox` for my projec, I get a full plain list of classes, properties and method, but mehtod or class annotations are not included in the generated docs.

I use the default `phpdox.xml` generated by `--skel`.

My annotations are like this:

    /**
     * Class Client
     * Lorem ipsum dolor.
     *
     * @author: Me Myself
     */

And this:

    /**
     * @method: setName
     *
     * @param: name: Name of client
     */
    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

**Comment by nzurita** [comment]
Sorry, it works properly, I was only looking in the first block "Synopsis"

**Comment by theseer** [comment]
Thanks for the heads up.
