### ISSUE TITLE
Disable phpmd enricher?

### ISSUE THREAD

**Issue by SafetyFast** [theseer/phpdox#400]
I'm new to phpdox so I'm pretty sure I'm doing something stupid.  

I generated the skeleton phpdox.xml file per the documentation.  I installed phpmd and enabled the enricher in phpdox.xml.  Works great. 

Now I would like to disable the phpmd check.  I commented out the phpmd enricher block in phpdox.xml, but when I generate the docs the phpmd violations are still reported.  I even deleted the phpmd.xml left from the previous run.

What silly thing am I likely to have overlooked? Thanks!

**Comment by theseer** [comment]
It's quite hard to figure out what might have gone wrong with such a small amount on info...

Can you paste some output and the actual config?

**Comment by SafetyFast** [comment]
Thank you for the quick response.  I found the problem and, of course, it was me. Sorry to have bothered you before doing more research.

**Comment by theseer** [comment]
No worries :) Glad you figured it out.
