### ISSUE TITLE
A deprecation bug found

### ISSUE THREAD

**Issue by pbrilius** [theseer/phpdox#404]
php phpdox.phar list

PHP Version: 7.4.9 (Linux)
PHPDox Version: 0.12.0
ErrorException: E_DEPRECATED 
Location: Unknown (Line 0)

Directive 'track_errors' is deprecated

No stacktrace available

**Comment by theseer** [comment]
The current code base has no "track_errors" anywhere.
I thus assume this to be something local on your system and not a bug in phpDox.
