### ISSUE TITLE
Dynamic properties creation are deprecated under PHP 8.2

### ISSUE THREAD

**Issue by dereckson** [theseer/phpdox#425]
Bootstrap and BootstrapAPI classes need properties explicitly declared.

The `private $logger` and `private $api` properties are the two needed for Bootstrap class, ``$logger` for BootstrapAPI. Private visiblity works well.

I can submit a PHP 7/8 compatible patch if needed.

**Comment by theseer** [comment]
Yes, please.

phpDox is suffering from neglect, I'm afraid.
