### ISSUE TITLE
Variables in XML files are not working

### ISSUE THREAD

**Issue by henvic** [theseer/phpdox#60]
I've tried both calling phpdox alone or using ant.

In both cases the ${basedir} and other variables aren't getting substituted.

I've tried both with phpdox 0.4 distributed trough PEAR and by cloning this repo.

I'm running PHP 5.4 (from Zend Server).

**Comment by fotografi** [comment]
>

**Comment by theseer** [comment]
?

**Comment by theseer** [comment]
@fotografi ?
